### ISSUE TITLE
JSON.toText() error

### ISSUE THREAD

**Issue by paulous** [NatLabs/serde#22]
Getting an  error on `JSON.toText(blob, field_keys);`. Any thoughts? Thanks!

```
public func motokoToJson(user : User) : async Text {
let blob = to_candid (user);

let field_keys = ["name", "id"];
JSON.toText(blob, field_keys);
};
```
error:
```
expression of type
  Result__6<Text, Text> = {#err : Text; #ok : Text}
cannot produce expected type
  TextMotoko(M0096)
expression of type
  (Blob, [Text])
cannot produce expected type
  (Blob, [Text], ?Options)Motoko(M0096)
```

**Comment by tomijaga** [comment]
Hey @paulous,

The `JSON.toText()` function has been updated and now includes an additional parameter for selecting options.
The readme has examples of how to use the new JSON API: https://github.com/NatLabs/serde?tab=readme-ov-file#json

Updating the code to this should fix the issue:
```motoko
JSON.toText(blob, field_keys, null);
```

**Comment by paulous** [comment]
hey, I actually tried that but the problem persists for me.

**Comment by tomijaga** [comment]
I forgot to mention that the functions returns a `Result<Text, Text>` for handling internal or formatting errors.
You can use the `switch` keyword to define what happens when the function succeeds (`#ok: Text`) and fails (`#err: Text `)

To illustrate, if the function succeeds, it will return the converted JSON text. On the other hand, if it fails, it will trap with an error message." 

```motoko
import Debug "mo:base/Debug";

public func motokoToJson(user : User) : async Text {
    let blob = to_candid (user);

    let field_keys = ["name", "id"];
    let result = JSON.toText(blob, field_keys, null);
    switch(result){
        case (#ok(json)) return json;
        case (#err(errMsg)) Debug.trap("motokoToJson() Failed:" # errMsg);
    };

};
```

**Comment by paulous** [comment]
Thanks! That helps me allot and increases my understanding.
